accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'accounts'
urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('user_register/', views.user_register, name='user_register'),
    path('logout/', views.logout_view, name='logout'),
    path('forgot_username/',views.forgot_username, name='forgot_username'),
    path('changepassword/',views.changepassword, name='changepassword'),
    path('activate/<str:activation_key>/<int:user_id>/', views.activate_account, name='activate'),
    path('accounts/reset_password/', 
         auth_views.PasswordResetView.as_view(template_name="password_reset.html"), 
         name='reset_password'),
    path('change_username/',views.change_username, name='change_username'),
    path('api/login/', views.login_view, name='login'),
]

blogs/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('news/', views.news, name='news'),
    path('details/<int:pk>/<int:author_id>/', views.details ,name='details'),
]

contact_us/urls.py
from django.urls import path
from .import views

app_name = 'contact_us'

urlpatterns = [
    path('form/',views.contact_us, name='form'),
]

homepage/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('Terms_and_Conditions/',views.Terms_and_Condition, name='Terms_and_Conditions'),
    path('lesson_details/<str:ref_code_book>/',views.lesson_details, name='lesson_details'),
    path('view_details/',views.view_details, name='view_details'),
    path('view_my_basket/',views.view_my_basket, name='view_my_basket'),
    path('add_basket_item/<str:chapter>/<str:ref_code_book>/<int:price>/',views.add_basket_item, name='add_basket_item'),
    path('check_out_payment/',views.check_out_payment, name='check_out_payment'),
    path('my_basket/<str:chapter>/<str:videos_url>/',views.my_basket, name='my_basket'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('add_whachtime/',views.add_whachtime, name='add_whachtime'),
    path('pay_success/',views.pay_success, name='pay_success'),
    path('pay_cancel/',views.pay_cancel, name='pay_cancel'),
    path('create_invoice/',views.create_invoice, name='create_invoice'),
    path('my_purchases/',views.my_purchases_items, name='my_purchases'),
    path('show_video/<str:chapter_title>/<str:part_title>/<str:part_video>/',views.show_video, name='show_video'),
    path('search/',views.searchbar, name='search'),
    path('lesson_details_searchbar/<str:ref_code_book>/<str:chapter_title>/',views.lesson_details_searchbar, name='lesson_details_searchbar'),
    path('book_content/<str:ref_code_book>/', views.book_content, name='book_content'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_class/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
     path('admin/', admin.site.urls),
     path('captcha/', include('captcha.urls')),
     path('tinymce/', include('tinymce.urls')),
     path('', include(('homepage.urls', 'homepage'), namespace='homepage')),
     path('accounts/', include(('accounts.urls','accounts'),namespace='accounts')),
     path('partnership/', include(('partnership.urls','partnership'),namespace='partnership')),
     path('contact_us/', include(('contact_us.urls','contact_us'),namespace='contact_us')),
     path('blogs/', include(('blogs.urls','blogs'),namespace='blogs')),
     path('primary/', include(('primary.urls','primary'),namespace='primary')),
     path('favicon.ico', RedirectView.as_view(url='/staticfiles/favico/favicon.ico')),
     path('reset/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),
         name="password_reset_confirm"),
     path('accounts/reset_password_sent/', 
         auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), 
         name='password_reset_done'),
     path('accounts/reset_password_complete/', 
         auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), 
         name='password_reset_complete'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/views.py
import mailtrap as mt
import random
import os
from .models import Mylogo,Image_news,Image_contact,Image_primaryschool,Image_register,Image_login,Image_t_c,Terms_and_Conditions,Partnership,Success_logo
from django.views.decorators.csrf import csrf_exempt, csrf_protect,requires_csrf_token
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render
import base64
import urllib.request
from unittest import loader
from django.views.decorators.csrf import csrf_exempt
import json
from datetime import datetime, date
from django.db.models import Q
from django.utils import timezone
from django.shortcuts import render
from django.template import loader
from django.urls import resolve
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
#from payments.models import Payment_details
from django.contrib.auth.decorators import login_required
from .models import my_purchases,Books_Images,Videos,Price_list,add_basket,display_video
import stripe
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from cloudinary.utils import cloudinary_url

pdfmetrics.registerFont(TTFont('DejaVuSans', 'fonts/DejaVuSans.ttf'))
pdfmetrics.registerFont(TTFont('Verdana', 'fonts/verdana.ttf'))

stripe.api_key = settings.STRIPE_SECRET_KEY
def searchbar(request):
    if request.method == "POST":
        char = request.POST.get('search')
        found = Videos.objects.filter(Q(chapter_title__iregex=char) | Q(part_title__iregex=char))
        if char=="":
            template = loader.get_template('searchbar.html')
            context = {
                'data': "",
            }
            return HttpResponse (template.render(context, request))
        elif not found.exists():
            template = loader.get_template('searchbar.html')
            context = {
                'data': "",
            }
            return HttpResponse (template.render(context, request))
        else:
            for i in found:
                refcode=i.ref_code_video
                general_info=Books_Images.objects.filter(ref_code_book=refcode)
            template = loader.get_template('searchbar.html')
            context = {
                'data': found,
                'gen_info':general_info,
                }
            return HttpResponse (template.render(context, request))
    else:
        return render(request,'searchbar.html')

@login_required
def books_image_view(request, *args, **kwargs):
    myurl=resolve(request.path_info).url_name
    mydata = Books_Images.objects.filter(ref_code=myurl).order_by('id')
    request.session['myurl'] = myurl
    template = loader.get_template('book_image.html')
    context = {
        'data': mydata,
        }
    return HttpResponse(template.render(context, request))

@login_required
def book_content(request,ref_code_book):
    url_context=request.build_absolute_uri()
    request.session['url_context'] =url_context
    ref_code_url=ref_code_book
    myurl = request.session.get('myurl')
    mydata=Books_Images.objects.filter(ref_code=myurl,ref_code_book=ref_code_url).values()
    book_title = mydata.values_list('book_title', flat=True).first()#
    request.session['book_title'] = book_title
    titles = Videos.objects.filter(ref_code=myurl,ref_code_video=ref_code_book).order_by('sorting_video').values_list('chapter_title', flat=True)
    list_capture = list(dict.fromkeys(titles))
    
    template = loader.get_template('book_content.html')
    context = {
        'data': mydata,
        'list': list_capture,
        }
    return HttpResponse (template.render(context, request))
 
@login_required
def view_my_basket(request):
    url=request.session.get('url')
    userid=request.user.id
    mybasket=add_basket.objects.filter(username_id=userid)
    template = loader.get_template('my_basket.html')
    context = {
        'basket':mybasket,
        'url':url,
        }
    return HttpResponse(template.render(context, request))

@login_required
def my_purchases_items(request):
    userid=request.user.id
    mypurchases=my_purchases.objects.filter(username_id=userid)
    template = loader.get_template('my_purchases.html')
    context = {
        'purchases':mypurchases,
        }
    return HttpResponse(template.render(context, request))

def homepage(request):
    logo=Mylogo.objects.all()
    news_image=Image_news.objects.all()
    contact_image=Image_contact.objects.all()
    primary_image=Image_primaryschool.objects.all()
    login_image=Image_login.objects.all()
    register_image=Image_register.objects.all()
    t_c_image=Image_t_c.objects.all()
    part_ship=Partnership.objects.all()
    context = {'logo': logo,
               'news_image':news_image,
               'contact_image':contact_image,
               'primaryschool_image':primary_image,
               'login_image':login_image,
               'register_image':register_image,
               't_c_image':t_c_image,
               'Partnership':part_ship,
               }
    return render(request, 'homepage.html', context)

@csrf_exempt
def Terms_and_Condition(request):
    logo=Mylogo.objects.all()
    t_c=Terms_and_Conditions.objects.all()
    context = {
        't_c':t_c,
        'mylogo':logo,
        }
    return render(request, "t_c.html", context)

@login_required         
def lesson_details(request,ref_code_book):
    ref_code_url=ref_code_book
    request.session['ref_code_url'] =ref_code_url
    if request.method == "POST":
        char=request.POST.get('your_name')
        if char==None:
            messages.success(request, 'Σφάλμα: Παρακαλώ επιλέξτε μία από τις επιλογές που σας δίνονται!')
            return render(request,'error.html')
        else:
            checkout_data=Books_Images.objects.filter(ref_code_book=ref_code_book)#book-image
            my_data=Videos.objects.filter(ref_code_video=ref_code_book,chapter_title=char).order_by('sorting_video')#videos
            sum=my_data.values_list('chapter_title')#total videos per chapter
            total=0
            for i in sum:
                total=total+1
            if my_data.filter(stage='primary',chapter_title=char).exists():
                request.session['char'] =char
                request.session['ref_code_book']=ref_code_book
                now=timezone.now()
                costumer=request.user.id
                access = my_purchases.objects.filter(username_id=costumer)
                if request.user.is_superuser or request.user.is_staff:
                    template = loader.get_template('list_all_chapter.html')
                    context = {
                        'video': my_data,
                        'all': total,
                        'data': checkout_data,
                        'title':char,
                        }
                    return HttpResponse(template.render(context, request))
                elif access.exists():
                    for i in access:
                        if i.end_date <now and i.chapter==char:
                            return HttpResponseRedirect(reverse('homepage:view_details'))
                        elif i.end_date>now and i.chapter==char:
                            template = loader.get_template('list_all_chapter.html')
                            context = {
                                'video': my_data,
                                'all': total,
                                'data': checkout_data,
                                'title':char,
                                }
                            return HttpResponse(template.render(context, request))
                
                        elif i.end_date>now and i.chapter=='Παρακολούθηση όλων των Κεφαλαίων':
                            template = loader.get_template('list_all_chapter.html')
                            context = {
                                'video': my_data,
                                'all': total,
                                'data': checkout_data,
                                'title':char,
                                }
                            return HttpResponse(template.render(context, request))
                        else:
                            return HttpResponseRedirect(reverse('homepage:view_details'))
                            
                else:
                    return HttpResponseRedirect(reverse('homepage:view_details'))
    
            elif my_data.filter(stage='secondary',chapter_title=char).exists():
                request.session['char'] =char
                request.session['ref_code_book']=ref_code_book
                now=timezone.now()
                costumer=request.user.id
                access = my_purchases.objects.filter(username_id=costumer)
                if request.user.is_superuser or request.user.is_staff:
                    template = loader.get_template('list_all_chapter.html')
                    context = {
                        'video': my_data,
                        'all': total,
                        'data': checkout_data,
                        'title':char,
                        }
                    return HttpResponse(template.render(context, request))
        
                if access.exists():
                    for i in access:
                        if i.end_date <now and i.chapter==char:
                            return HttpResponseRedirect(reverse('homepage:view_details'))
                
                        elif i.end_date>now and i.chapter==char:
                            template = loader.get_template('list_all_chapter.html')
                            context = {
                                'video': my_data,

homepage/templates/homepage/book_content.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="el">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'homepage/book_content.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
    <title>Περιεχόμενα</title>
</head>
<body>
    <!--<script>
        document.addEventListener("contextmenu", function (e) {
        e.preventDefault();
    });
    </script>!-->
    {% for x in data %}
        <h1>{{x.book_title}}</h1>
        <form action="{% url 'homepage:lesson_details' x.ref_code_book %}" method="post">
            {% csrf_token %}
            <select name="your_name" class='select_value'title="Select an option">
                <option selected disabled hidden>-Επιλογή Κεφαλαίου-</option>
                <option class="droplist">Παρακολούθηση όλων των Κεφαλαίων</option>
                {% for j in list %}
                    <option class="droplist" type="text" value="{{j}}">{{j}}</option>
                {% endfor %}
            </select>       
            <button class='button_chapter' type="submit">Προβολή</button>
            
        </form>
        
        <div class="text">
            {% for j in data %}
                {% if j.book %}
                    <a id="downbook" href="{{ j.book }}" target="_blank">Κατέβασε το αρχείο σε pdf</a>
                {% endif %}
            {% endfor %}
            <p id='content'>Περιεχόμενα</p>
            <p class="text1">{{ x.content|safe }}</p><br>
        </div>
        <a href="{% url 'homepage:homepage' %}" class="button">Αρχική Σελίδα</a>
        <a href="#" id="backButton" class="button1">Πίσω</a>
        <a href="#" id="topLink" class="top-link">Κορυφή Σελίδας</a>
        <script>
            document.addEventListener("scroll", function() {
                let topLink = document.querySelector(".top-link");
                if (window.innerHeight + window.scrollY >= document.body.offsetHeight) {
                    topLink.style.display = "block"; // Εμφανίζεται όταν ο χρήστης φτάσει κάτω
                } else {
                    topLink.style.display = "none"; // Κρύβεται αν ο χρήστης δεν είναι στο κάτω μέρος
                }
            });
        </script>
            

        <script>
            document.getElementById('topLink').addEventListener('click', function(event) {
                event.preventDefault();
                window.scrollTo({ top: 0, behavior: 'smooth' });
                localStorage.setItem('topClicked', 'true');
            });
            document.getElementById('backButton').addEventListener('click', function(event) {
                if (localStorage.getItem('topClicked') === 'true') {
                    history.go(-1);
                } else {
                    history.go(-1);
                }
                localStorage.removeItem('topClicked');
            });
        </script>
        
        
    {% endfor %} 
    
</body>

</html>
{% endblock content %}

homepage/templates/homepage/book_image.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="el">
    
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'homepage/book_image.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
        <title>Εξώφυλλο Βιβλίών</title>
    </head>
    
<body>
    <!--<script>
        document.addEventListener("contextmenu", function (e) {
        e.preventDefault();
    });
    </script>-->
    {% for x in data %}
        <br />
        <h1>{{x.book_title}}</h1>
        <a type="button" class="button1" href="{% url 'homepage:book_content' x.ref_code_book %}">Περιεχόμενο</a>
        <a href="{% url 'homepage:homepage' %}" class="button2">Πίσω</a>
        <img class="image" src="{{x.image}}" alt="Εξωφυλλο Βιβλίου" title="Εξωφυλλο Βιβλίου">
        <br />
        <hr>
    {% endfor %}

</body>
</html>

{% endblock content %}

homepage/templates/homepage/footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="{% static 'homepage/footer.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <footer>
        <div class="container">
            <div class="footer-columns">
                <div class="footer-column">
                    <h3>Τι Προσφέρουμε</h3>
                    <p>Παρέχουμε διαδικτυακά μαθήματα για μαθητές Δημοτικού, Γυμνασίου και Λυκείου, σύμφωνα με τα σχολικά εγχειρίδια της Κύπρου 
                        και της Ελλάδας, με οργανωμένη και κατανοητή διδασκαλία 📖 💻 🌍</p>
                </div>
                <div class="footer-column">
                    <h3>Quick Links</h3>
                    <ul>
                        <li><a href="{% url 'homepage:homepage' %}">Home</a></li>
                        <li><a href="{% url 'contact_us:form' %}">Contact</a></li>
                    </ul>
                </div>
                <div class="footer-column">
                    <h3>Επικοινωνία</h3>
                    <ul>
                        <li><a href="mailto:cpsoftwarecreation@outlook.com">Email: cpnetuni@outlook.com</a></li>
                        <li><a href="tel:0035799899041">Phone Cy: 00357-99899041</a></li>
                        <li><a href="tel:00447731869171">Phone UK: 0044-</a></li>
                        <li>Διεύθυνση: Nicosia, Cyprus</li>
                        <li>Διεύθυνση: London, United Kingdom</li>
                    </ul>
                </div>
            </div>
            <div class="social-icons">
                <a href="https://www.facebook.com/profile.php?id=61572742991174" target="_blank">
                    <i class="fa fa-facebook"></i> Facebook
                </a>
                <a href="https://www.instagram.com/cpnetuni/" target="_blank">
                    <i class="fa fa-instagram"style="font-size:24px;color:red"></i> Instagram
                </a>
            </div>
            <p>&copy; 2025 C.P Education For All. All rights reserved. <br> This site was created by C.P Software Creation.</p>
        </div>
    </footer>
</body>

homepage/templates/homepage/lesson_details.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="el">
    
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'homepage/lesson_details.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        <title>Checkout</title>
    </head>
    
<body>
    <!--<script>
        document.addEventListener("contextmenu", function (e) {
        e.preventDefault();
    });
    </script>-->
    
    {% for x in data %}
        <h1>{{x.book_title}}</h1>
        <ul>
            <li><a href="{% url 'homepage:homepage' %}">Αρχική Σελίδα</a></li>
            <li><a href="{% url 'homepage:view_my_basket' %}"><i class="fa fa-shopping-cart" style="font-size:20px;color:red"></i>  Το Καλάθι μου</a></li>
            <li><a href="{% url 'homepage:add_basket_item' chapter ref_code_book price %}" onclick="alert('Επιτυχία Καταχώρησης')">Προσθήκη στο Καλάθι</a></li>
            <li><a onClick="javascript:history.go(-1);" id="backButton">Πίσω</a></li>
        </ul>
        
        <script>
            document.getElementById('topLink').addEventListener('click', function(event) {
                event.preventDefault();
                window.scrollTo({ top: 0, behavior: 'smooth' });
                localStorage.setItem('topClicked', 'true');
            });
            document.getElementById('backButton').addEventListener('click', function(event) {
                if (localStorage.getItem('topClicked') === 'true') {
                    history.go(-1);
                } else {
                    history.go(-1);
                }
                localStorage.removeItem('topClicked');
            });
        </script>
        {% if messages %}
            <div class="msg">
                {% for message in messages %}
                    <a {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </a>
                {% endfor %}
            </div>
        {% endif %}

        {% if check == 1 %}
            <p id='p'>Τιμή: €{{price}}</p>
        {% else %}
            <p id='p'>Τιμή: €{{price}}</p>
        {% endif %}
        
        <p id='chapter' ><span id='span1'>Έχετε επιλέξει:</span> {{chapter}}</p>
        <p class='info' ><span id='span2'>Προσοχή: </span>Ελέγξτε το καλάθι σας πριν απο την εκτέλεση της αγοράς!</p>
        <img class="image" src="{{x.image}}" alt="Εξωφυλλο Βιβλίου" title="Εξωφυλλο Βιβλίου"> 
        <a href="{% url 'homepage:check_out_payment' %}"  class="buy_now">Αγορά</a>
        
        <hr></hr>
        <p>Τι περιλαμβάνει:</p>
        <div class='whatinclude'>
            {% for j in what_includes %}
                <div class="container" {% if forloop.counter > 2 %}style="display: none;"{% endif %}>
                    <div class="div1">
                        <img class='icon' src="https://res.cloudinary.com/hotitu8ux/image/upload/v1743025309/4503949_nxtes5.png" alt="icon" width="20" height="20">
                        <p class='wh_incl'>{{ j.what_includes|safe }}</p>
                    </div>
                </div>
            {% endfor %}
            <div id="message" class="message">Δεν έχετε πρόσβαση</div>
            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    const inclTextElements = document.querySelectorAll('.wh_incl');
                    const message = document.getElementById('message');

                    inclTextElements.forEach(function(inclText) {
                        inclText.addEventListener('mouseenter', function(event) {
                            message.style.display = 'block';
                            message.style.left = event.pageX + 'px';
                            message.style.top = event.pageY + 'px';
                        });
                        inclText.addEventListener('mouseleave', function() {
                            message.style.display = 'none';
                        });
                    });
                });
            </script>

            {% if what_includes|length > 2 %}
                <button id="read-more-btn" class='read-more-btn'>Περισσότερα</button>
                <button id="read-less-btn" class='read-less-btn'>Λιγότερα</button>
            {% endif %}
        </div>
        
        <script>
            document.addEventListener("DOMContentLoaded", function() {
                var readMoreBtn = document.getElementById("read-more-btn");
                var readLessBtn = document.getElementById("read-less-btn");
        
                readMoreBtn.addEventListener("click", function() {
                    document.querySelectorAll('.container').forEach(function(container, index) {
                        if (index > 1) {
                            container.style.display = 'block';
                        }
                    });
                    readMoreBtn.style.display = 'none';
                    readLessBtn.style.display = 'inline';
                });
        
                readLessBtn.addEventListener("click", function() {
                    document.querySelectorAll('.container').forEach(function(container, index) {
                        if (index > 1) {
                            container.style.display = 'none';
                        }
                    });
                    readLessBtn.style.display = 'none';
                    readMoreBtn.style.display = 'inline';
                });
            });
        </script>
        

        <br><hr></hr>
        <p id='p2'>Επιστροφή χρημάτων ισχύει μόνο αν το video δεν προβληθεί.<br/><a href="{% url 'homepage:Terms_and_Conditions' %}" class="accept">Διάβασε όρους και προυποθέσεις<a/></p>
        <p id='p1'>***Η υπηρεσία διαρκεί ένα ακαδημαϊκο έτος από την ημέρα αγοράς</p> 
    {% endfor %}
    <a href="#" id="topLink" class="top-link">Κορυφή Σελίδας</a>
    
    

</body>
</html>

{% endblock content %}

homepage/templates/homepage/my_basket.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="el">
    
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" href="{% static 'homepage/my_basket.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
        <title>Checkout</title>
    </head>

<body>
    <script>
        document.addEventListener("contextmenu", function (e) {
        e.preventDefault();
    });
    </script>

    <h1>Το Καλάθι μου</h1>
        {% for x in basket %}
            <a href="{% url 'homepage:check_out_payment' %} " class="buy_now">Εκτέλεση Αγορών</a>
            <a href="{% url 'homepage:homepage' %}" class="button1">Αρχική Σελίδα</a>
            <a onClick="javascript:history.go(-1);" class="button2">Πίσω</a>
            <div class='center'>
                <p id='p3'>{{x.book_title}}</p>
                <img class="image" src="{{x.image}}" >
                <br/>
                <p><a id="p1" href="{% url 'homepage:my_basket' x.chapter x.videos_url %}"> {{x.chapter}} <span>{{x.part}}</span></a></p>
                <a  id="p2"  href="{% url 'homepage:delete' x.id %}">Διαγραφή</a>
                <p></p>
                <hr color='black'>
            </div>
                
                
        {% empty %}
            <p id='p4'>Το Καλάθι σας είναι Άδειο</p>
            <a href="{% url 'homepage:homepage' %}" class="button1">Αρχική Σελίδα</a>
            <a onClick="javascript:history.go(-1);" class="button2">Πίσω</a>
        {% endfor %}
        
        
        
    
</body>
</html>
{% endblock content %}

homepage/templates/homepage/searchbar.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="el">
    
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'homepage/searchbar.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
        <title>Checkout</title>
    </head>

<body>

    <h1>Αποτελέσματα Αναζήτησης</h1>
    {% if user.is_authenticated %}
        {% if data %}
            {% for x in data %}
                <div class='center'>
                    <a href="{% url 'homepage:homepage' %}" class="button1">Πίσω</a>
                    {% for j in gen_info %}
                        <p id='p5'>{{j.book_title}}</p>
                        <img class="image" src="{{j.image}}" >
                        <p><a id="p3" href="{% url 'homepage:lesson_details_searchbar' j.ref_code_book x.chapter_title %}"> {{ x.part_title }} {{ x.part_video }} </a></p>
                    {% endfor %}
                    <p></p>
                    <hr color='black'>
                    <br/>
                    </div>
            {% endfor %}
        {% else %}
            <a href="{% url 'homepage:homepage' %}" class="button1">Πίσω</a>
            <p id='p4'>0 αποτελέσματα. <span>Παρακαλώ ελέγξτε την γλώσσα, την ορθογραφία και τον τονισμό των λέξεων που αναζητείτε!</span></p>
        {% endif %}
    {% else %}
        {% if data %}
            {% for x in data %}
                <div class='center'>
                <a href="{% url 'homepage:homepage' %}" class="button1">Πίσω</a>
                {% for j in gen_info %}
                    <p id='p5'>{{j.book_title}}</p>
                    <img class="image" src="{{j.image}}" >
                    <p><a id="p3" href="{% url 'accounts:login_user' %}"> {{ x.part_title }} {{ x.part_video }} </a></p>
                {% endfor %}
                <p></p>
                <hr></hr>
                <br/>
                </div>
            {% endfor %}
        {% else %}
            <a href="{% url 'homepage:homepage' %}" class="button1">Πίσω</a>
            <p id='p4'>0 αποτελέσματα.<br><br> <span>Παρακαλώ ελέγξτε την γλώσσα, την ορθογραφία και τον τονισμό των λέξεων που αναζητείτε!</span></p>
        {% endif %}
    {% endif %}
        
        
    
</body>
</html>
{% endblock content %}