accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'accounts'
urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('user_register/', views.user_register, name='user_register'),
    path('logout/', views.logout_view, name='logout'),
    path('forgot_username/',views.forgot_username, name='forgot_username'),
    path('changepassword/',views.changepassword, name='changepassword'),
    path('activate/<str:activation_key>/<int:user_id>/', views.activate_account, name='activate'),
    path('accounts/reset_password/', 
         auth_views.PasswordResetView.as_view(template_name="password_reset.html"), 
         name='reset_password'),
    path('change_username/',views.change_username, name='change_username'),
    path('api/login/', views.login_view, name='login'),
]

blogs/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('news/', views.news, name='news'),
    path('details/<int:pk>/<int:author_id>/', views.details ,name='details'),
]

homepage/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('Terms_and_Conditions/',views.Terms_and_Condition, name='Terms_and_Conditions'),
    path('lesson_details/<str:ref_code_book>/',views.lesson_details, name='lesson_details'),
    path('view_details/',views.view_details, name='view_details'),
    path('view_my_basket/',views.view_my_basket, name='view_my_basket'),
    path('add_basket_item/<str:chapter>/<str:ref_code_book>/<int:price>/',views.add_basket_item, name='add_basket_item'),
    path('check_out_payment/',views.check_out_payment, name='check_out_payment'),
    path('my_basket/<str:chapter>/<str:videos_url>/',views.my_basket, name='my_basket'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('add_whachtime/',views.add_whachtime, name='add_whachtime'),
    path('pay_success/',views.pay_success, name='pay_success'),
    path('pay_cancel/',views.pay_cancel, name='pay_cancel'),
    path('create_invoice/',views.create_invoice, name='create_invoice'),
    path('my_purchases/',views.my_purchases_items, name='my_purchases'),
    path('show_video/<str:chapter_title>/<str:part_title>/<str:part_video>/',views.show_video, name='show_video'),
    path('search/',views.searchbar, name='search'),
    path('lesson_details_searchbar/<str:ref_code_book>/<str:chapter_title>/',views.lesson_details_searchbar, name='lesson_details_searchbar'),
    path('book_content/<str:ref_code_book>/', views.book_content, name='book_content'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_class/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
     path('admin/', admin.site.urls),
     path('captcha/', include('captcha.urls')),
     path('tinymce/', include('tinymce.urls')),
     path('', include(('homepage.urls', 'homepage'), namespace='homepage')),
     path('accounts/', include(('accounts.urls','accounts'),namespace='accounts')),
     path('partnership/', include(('partnership.urls','partnership'),namespace='partnership')),
     path('contact_us/', include(('contact_us.urls','contact_us'),namespace='contact_us')),
     path('blogs/', include(('blogs.urls','blogs'),namespace='blogs')),
     path('primary/', include(('primary.urls','primary'),namespace='primary')),
     path('favicon.ico', RedirectView.as_view(url='/staticfiles/favico/favicon.ico')),
     path('reset/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),
         name="password_reset_confirm"),
     path('accounts/reset_password_sent/', 
         auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), 
         name='password_reset_done'),
     path('accounts/reset_password_complete/', 
         auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), 
         name='password_reset_complete'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

class accept_t_c(models.Model):
    username=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=True)
    accept_terms = models.BooleanField(default='True')
class UserActivation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    activation_key = models.CharField(max_length=40)
    activated = models.BooleanField(default=False)

accounts/views.py
from django.contrib.auth import logout
import uuid
from django.contrib import messages,auth
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt, csrf_protect,requires_csrf_token
import mailtrap as mt
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.urls import reverse
from .models import UserActivation,accept_t_c
from homepage.models import Mylogo
from rest_framework.decorators import api_view


def logout_view(request):
    logout(request)
    return redirect('/')

@requires_csrf_token    
@csrf_protect  #you can refresh page when you auth
def login_user(request,*args, **kwargs):
    logo=Mylogo.objects.all()
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            us_id = User.objects.get(username=username)
            id_user = us_id.id
            active_users = UserActivation.objects.filter(user_id=id_user,activated=True).exists()
            if active_users and user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse("homepage:homepage"))      
                #request.session['log_in']=log_in
                #request.session.modified = True
            #return HttpResponseRedirect(reverse("homepage:user_on"))       
            elif user is None:
                messages.error(request,"Έχετε καταχωρήσει λανθασμένα το Username ή το Password!")
                return render(request,'login.html')
            elif not active_users :
                messages.error(request,"Παρακαλώ επιβεβαιώστε το Email σας στον σύνδεσμο που σας έχει σταλεί")
                return render(request,'login.html')
        else:
            messages.error(request,"Έχετε καταχωρήσει λανθασμένα το Username ή το Password!")
            return render(request,'login.html')
    else:
        context = {'logo': logo,
        }
        return render(request,'login.html',context)
    
@api_view(['POST'])
def login_view(request):
    username = request.data.get('username')
    password = request.data.get('password')

    user = authenticate(request, username=username, password=password)
    if user is not None:
        return JsonResponse({'message': 'Login successful!'})
    else:
        return JsonResponse({'error': 'Invalid credentials'}, status=400)
    
@requires_csrf_token
@csrf_protect
def user_register(request,):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        accept_terms=request.POST.get('t_c')
        
        if password1==password2:
            has_length_greater_than_8 = len(password1) >= 8
            has_uppercase = any(i.isupper() for i in password1)
            has_lowercase = any(i.islower() for i in password1)
            has_digit = any(i.isdigit() for i in password1)
            has_special_character = any(not i.isalnum() for i in password1)
            if has_length_greater_than_8 and has_uppercase and has_lowercase and has_digit and has_special_character:
                if User.objects.filter(username=username).exists() and User.objects.filter(email=email).exists():
                    messages.error(request,'Το Username και το Email ανήκουν σε άλλο χρήστη!')
                    return render(request,('register.html'))
        
                elif User.objects.filter(email=email).exists():
                    messages.error(request,'Το Email χρησιμοποιείται από άλλο χρήστη!')
                    return render(request,('register.html'))
                     
                elif User.objects.filter(username=username).exists():
                    messages.error(request,'Το Username χρησιμοποιείται από άλλο χρήστη!')
                    return render(request,('register.html'))
                else:
                    #user2=accounts_details.objects.create(username=username,password=password1,email=email,first_name=first_name,last_name=last_name)
                    user=User.objects.create_user(username=username, password=password1, email=email, first_name=first_name, last_name=last_name)
                    t_c=accept_t_c.objects.create(accept_terms=accept_terms)
                    user.save()
                    #user2.save()
                    t_c.save()
                    #time.sleep(2)
                    user_id=User.objects.filter(username=username,email=email)
                    for i in user_id:
                        id_user=i.id
                    activation_key = str(uuid.uuid4())
                    user_activation = UserActivation(user_id=id_user, activation_key=activation_key)
                    user_activation.save()
                    activation_link = reverse('accounts:activate', kwargs={'activation_key': activation_key, 'user_id': id_user})
                    text=f'Πιέστε τον σύνδεσμο για ενεργοποίηση του λογαριασμού σας στο cpnetuni.com : {request.build_absolute_uri(activation_link)} '

                    mail = mt.Mail(
                        sender=mt.Address(email="no-reply@cpnetuni.com", name="Επιτυχία Εγγραφής"),
                        to=[mt.Address(email=email)],
                        subject="Ενεργοποίηση Λογαριασμού",
                        text=text,
                        category="Εγγραφές",
                    )

                    client = mt.MailtrapClient(token="388ed30f960c9bd511b4cbd740d05b7d")
                    client.send(mail)
                    
                    messages.add_message(request, messages.INFO,'Επιτυχία Εγγραφής. Σας έχει αποσταλεί σύνδεσμος ενεργοποίησης λογαριασμού 🚀. ')
                    return HttpResponseRedirect(reverse("homepage:homepage"))
            else:
                messages.error(request,'Ο Κωδικός σας δεν πληρεί τις προύποθέσεις (Τουλάχιστο 8 ψηφία και να περιέχει 1 αριθμό 1 κεφαλάιο και 1 ειδικό χαρακτήρα)')
                return render(request,('register.html'))
        
        else:
            messages.info(request,'Ο Κωδικός επαλήθευσης είναι λανθασμένος!',extra_tags="pswreg")
            return render(request,('register.html'))
    else:
        return render(request,('register.html'))
            
            

def activate_account(request, activation_key,user_id):
    try:
        #mylogo_home=logo.objects.filter(title='mylogo')
        user_activation = UserActivation.objects.filter(user_id=user_id,activation_key=activation_key)
        for i in user_activation:
            i.activated = True
            i.save()
        messages.error(request,'Έχετε επιβεβαιώσει με επιτυχία το Ηλεκτρονικό σας Ταχυδρομείο')
        #content={
            #'mylogo':mylogo_home,
        #}
        return redirect('homepage:homepage') 

    except UserActivation.DoesNotExist:
        messages.error(request,'Αποτυχία επιβεβαίωσης ηλεκτρονικού ταχυδρομίου')
        #content={
            #'mylogo':mylogo_home,
        #}
        return redirect('homepage:homepage')

@requires_csrf_token
@csrf_protect
def forgot_username(request):
    if request.method == "POST":
        email = request.POST.get('email')
        if User.objects.filter(email=email).exists():
            for e in User.objects.filter(email=email):
                username=e.username
                text='Το Username σας είναι : {}'.format(username)
                mail = mt.Mail(
                    sender=mt.Address(email="no-reply@cpnetuni.com", name="Επαναφορά Ονόματος Χρήστη"),
                    to=[mt.Address(email=email)],
                    subject="Επαναφορά Username",
                    text=text,
                    category="Επαναφορά Username",
                )

                client = mt.MailtrapClient(token="388ed30f960c9bd511b4cbd740d05b7d")
                client.send(mail)
            return render(request,'send_username_done.html')
                
        else:
            messages.error(request, 'Το Email που καταχωρήσατε δεν είναι συνδεδεμένο με κάποιο λογαριασμο.\nΠαρακαλώ ελέγξτε το Email και ξανά προσπαθήστε!')
            return render(request,'send_username.html')      
    else:
        return render(request,('send_username.html'))
    
@requires_csrf_token
@csrf_protect
def changepassword(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        user = auth.authenticate(username=username, password=password1)
        if user is not None:
            user=User.objects.get(username=username)
            if password1!=password2:
                user.set_password(password2)
                user.save()
                messages.warning(request,"Επιτυχής αλλαγή Κωδικού Πρόσβασης")
                return redirect('homepage:homepage')
            else:
                messages.warning(request,"Ο Κωδικός σας είναι ο ίδιος με τον προηγούμενο! Παρακαλώ καταχωρήστε καινούργιο κωδικό πρόσβασης!")
                return render(request,'change_password.html')
        else:
            messages.warning(request,"Έχετε καταχωρήσει λανθασμένα το Username ή το Password!")
            return render(request,'change_password.html')
    else:
        return render(request,'change_password.html')

@requires_csrf_token
@csrf_protect
def change_username(request):
    user_email = request.user.email
    if request.method == 'POST':
        usernamenew = request.POST.get('username')

accounts/templates/accounts/change_password.html
{% block content %} 
{% load static %}
<!DOCTYPE html>
<html lang="el">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'accounts/change_password.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
    <title>Εγγραφή</title>
  </head>
  <body>
    <h1>Αλλαγή Κωδικού Πρόσβασης</h1>
    <a onClick="javascript:history.go(-1);" class="button2">Πίσω</a>
        <form method="POST" action="" autocomplete="off">
          {% csrf_token %}
                
                <label for="username" id="usr">Username: </label></br>
                <input type="text" name="username" placeholder="User name" required="" autocomplete="off"><br/>

                <label for="password1" id="psw1">Old Password: </label></br>
                <input type="password" name="password1" placeholder="Password" required="" autocomplete="new-password"><br/>
                
                <label for="password2" id="psw2">New Password: </label></br>
                <input type="password" name="password2" placeholder="Password" required="" autocomplete="new-password"><br/>
                
                <label for="password2" id="psw3">Confirm Password: </label></br>
                <input type="password" name="password3" placeholder="Confirm Password" required="" autocomplete="new-password"><br/>
                
                <button>Καταχώρηση</button>
        </form>
        
        <div id="msg1">
          {% if messages %}
            {% for message in messages %}
              <p><a {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.warning %}{% endif %}{{ message }}
              </p>
            {% endfor %}
          {% endif %}
        </div>
  </body>
</html>
{% endblock content %}

accounts/templates/accounts/login.html
{% block content %} 
{% load static %}
<!DOCTYPE html>
<html lang="el">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'accounts/login.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
    <title>Σύνδεση</title>
  </head>
  <body>
    <h1>Σύνδεση</h1>
    <a href="{% url 'homepage:homepage' %}" class="btn33">Αρχική Σελίδα</a>
    
  
    <form method="POST" action="" autocomplete="off">
      {% csrf_token %}
      <div class="border-box">
        <label for="uname" id="un">Username: </label><br/>
        <input type="text" name="username" placeholder="Enter Username" id="uname"required="" autocomplete="off"><br/>
        <label for="upass" id="ps">Password: </label><br/>
        <input type="password" name="password" placeholder="Enter Password" id="upass"required="" autocomplete="new-password"><br/>
      </div>
      <input type="checkbox" id='viewcode' onclick="togglePasswordVisibility()">Εμφάνιση Κωδικού Ασφαλείας</input><br>
      <script>
        function togglePasswordVisibility() {
          var x = document.getElementById("upass");
          if (x.type === "password") {
            x.type = "text";
          } else {
            x.type = "password";
          }
        }
      </script>
      
      <button type="submit" value="Login"  id="submit">Login</button>
    </form>
    <p class='p1'>Αν <span style="color:red;">ΔΕΝ</span> έχετε κάνει εγγραφή, παρακαλώ πατήστε τον σύνδεσμο <a href="{% url 'accounts:user_register' %}"><span>Για Εγγραφή</span></a></p>
    <p id='p2'><a href="{% url 'accounts:forgot_username' %}"> <span> Ξεχάσατε το Username; </span> </a></p>
    <p id='p3'><a href="{% url 'accounts:reset_password' %}"> <span> Ξεχάσατε τον Κωδικό; </span> </a></p>
    <div id="msg">
      {% if messages %}
        {% for message in messages %}
          <p><a {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.error %}{% endif %}{{ message }}
          </p>
        {% endfor %}
      {% endif %}
    </div>
      
  </body>
</html>
{% endblock content %}

accounts/templates/accounts/password_reset.html
{% block content %} 
{% load static %}
<!DOCTYPE html>
<html lang="el">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'accounts/password_reset.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
  <body>
    <h1>Επαναφορά Κωδικού Πρόσβασης</h1>
    <a  href="{% url 'homepage:homepage' %}" class="button1">Αρχική Σελίδα</a>
    <a  href="{% url 'accounts:login_user' %}" class="button2">Σύνδεση</a>
      <form method="POST" action="">
        {% csrf_token %}
        <div class="border-box">
          <label for="email" id="un">Email: </label><br>
          <input type="email" name="email" placeholder="Email" id="uname"required=""><br/>
        </div>
        <button type="submit" id="submit">Αποστολή</button><br>
      </form>
      <p id='title'><span>Ξεχάσατε τον κωδικό σας;</span> Καταχωρήστε το <span>Email </span>σας και θα σας αποσταλούν οδηγίες
      επαναφοράς!</p>
  </body>
</html>
{% endblock content %}

accounts/templates/accounts/password_reset_done.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="el">
    
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" href="{% static 'accounts/password_reset_done.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
        <title>Checkout</title>
    </head>
    <body>
        <h1>Επιτυχής Επαναφορά Κωδικού Πρόσβασης</h1><br/>
        <p>Ο Κωδικός σας έχει αλλάξει.</p><br/>
        <a class='button' href="{% url 'accounts:login_user' %}">Σύνσεση</a>
    </body>
</html>
{% endblock content %}

accounts/templates/accounts/password_reset_form.html
{% block content %} 
{% load static %}
<!DOCTYPE html>
<html lang="el">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
    <link rel="stylesheet" href="{% static 'accounts/password_reset_form.css' %}">
    <title>Επαναφορά Κωδικου</title>
</head>
<body>
    <h1>Επαναφορά Κωδικού Πρόσβασης</h1>
        <form method="POST" class="password-reset-form">
            {% csrf_token %}
            {{form.as_p}}
            <input class="submit" type="submit" name="Update Password"><br />
        </form>
</body>
</html>
{% endblock content %}

accounts/templates/accounts/password_reset_sent.html
{% block content %} 
{% load static %}
<!DOCTYPE html>
<html lang="el">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Επιτυχής Επαναφορά</title>
    <link rel="stylesheet" href="{% static 'accounts/password_reset_sent.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
  </head>
  <body>
    <h1>Επαναφορά Κωδικού Πρόσβασης</h1>
    <p>Σας έχουμε αποστείλει οδηγίες επαναφοράς κωδικού πρόσβασης.
      Αν το Email  που έχετε καταχωρήσει αντιστοιχει σε εγγεγραμμένο 
      λογαριασμό, θα λάβετε σύνδεσμο επαναφοράς άμεσα!</p>
    
    <p>Αν δεν λάβετε άμεσα τις οδηγίες επαναφοράς, παρακαλώ ελέγξετε
        το Email που καταχωρήσατε, αν είναι συνδεδεμένο με κάποιο λογαριασμό
        στο <span>Net Uni</span><span id='a'>-School for All</span>!</p>
    <a href="{% url 'homepage:homepage' %}" class="button1">Αρχική Σελίδα</a>
    <a href="{% url 'accounts:login_user' %}" class="button2">Σύνδεση</a>

  </body>
</html>
{% endblock content %}

accounts/templates/accounts/register.html
{% block content %} 
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Εγγραφή</title>
    <link rel="stylesheet" href="{% static 'accounts/register.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
  </head>
<body>
  
  <form method="POST" action="{% url 'accounts:user_register' %}" autocomplete="off">
    {% csrf_token %}
    <div id="container">
      <label for="first_name" id="name">First Name: </label><br>
      <input type="text" name="first_name" placeholder="First Name:"required="" size="30"/><br>
      
      <label for="last_name" id="name">Last Name: </label><br>
      <input type="text" name="last_name" placeholder="Last Name:"required="" size="30"/><br>
   
      <label for="email" id="name">Email: </label><br>
      <input type="email" name="email" placeholder="Email" required="" size="30"/><br>
 
      <label for="username" id="usr">Username: </label><br>
      <input type="text" name="username" placeholder="User name" required="" size="30" /><br>
     
      <label for="password1" id="psw">Password: </label><br>
      <input type="password" name="password1" placeholder="Password" required="" size="30"/><br>
     
      <label for="password2" id="psw">Confirm Password: </label><br>
      <input type="password" name="password2" placeholder="Confirm Password" required="" size="30"/><br>
      
      <label for="t_c" class="t_and_c"> 
        <br>
        Κάνοντας κλικ, επιβεβαιώνω ότι είμαι άνω των 18   
        <br>
        ετών και συμφωνώ με τους Όρους, τις Προϋποθέσεις
        <br>
        και την Πολιτική Απορρήτου της <span id='one'>CP</span> <span id='two'>School for</span> <span id='three'>All</span>
        <br>
        και συμφωνώ να συμμορφώνομαι με τον
        <br>
        Κώδικα Δεοντολογίας
      </label>
      <br>  
      <input type="checkbox" id="t_c1" name="t_c" required="" value="True"/><br>
 
      <a href="{% url 'homepage:Terms_and_Conditions' %}" id="accept">Όροι και Προυποθέσεις</a><br>
      <div id="msg1">
        {% if messages %}
          {% for message in messages %}
            <p><a {% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.error %}{% endif %}{{ message }}
            </p>
          {% endfor %}
        {% endif %}
      </div>
      <button>Εγγραφή</button><br>
    </div>
    <h1>Εγγραφή</h1>
    <a href="{% url 'homepage:homepage' %}" class="button1">Αρχική Σελίδα</a>
    <a href="{% url 'accounts:login_user' %}" class="button2">Σύνδεση</a>
  </form>
  
</body>
</html>
{% endblock content %}

accounts/templates/accounts/send_username.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'accounts/send_username.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >

<body>
    <h1>Επαναφορά Username</h1>
    <a href="{% url 'homepage:homepage' %}" class="button1">Αρχική Σελίδα</a>
    <a href="{% url 'accounts:login_user' %}" class="button2">Σύνδεση</a>
    <form method="POST" action="">
        {% csrf_token %}
        <div class="border-box">
            <label for="email" id="un">Email: </label>
            <input type="email" name="email" placeholder="Email" id="uname" required=""><br />
            <button type="submit" id="submit">Αποστολή</button>
        </div>
    </form>
    <p id='title'><span>Ξεχάσατε τον Username σας;</span> Καταχωρήστε το <span>Email </span>σας και θα λάβετε το Username μέσω Email!</p>
    <p style="color:blue;">
    {% if messages %}
        {% for message in messages %}
            {% if message.tags %}
            {% endif %}{{ message }}
        {% endfor %}
    {% endif %}</p>
</body>

</html>
{% endblock content %}

accounts/templates/accounts/send_username_done.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'accounts/send_username_done.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
</head>
<body>
    <a href="{% url 'homepage:homepage' %}" class="btn33">Αρχική Σελίδα</a>
    <a href="{% url 'accounts:login_user' %}" class="button2">Σύνδεση</a>
    <h1 style="color:blue;">Επιτυχής Αποστολή Username</h1>
    <p>Το Username σας θα το λάβετε άμεσα στο Ηλεκτρονικό σας Ταχυδρομείο!</p>
    
</body>
</html>

{% endblock content %}