blogs/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('news/', views.news, name='news'),
    path('details/<int:pk>/<int:author_id>/', views.details ,name='details'),
]

homepage/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('Terms_and_Conditions/',views.Terms_and_Condition, name='Terms_and_Conditions'),
    path('lesson_details/<str:ref_code_book>/',views.lesson_details, name='lesson_details'),
    path('view_details/',views.view_details, name='view_details'),
    path('view_my_basket/',views.view_my_basket, name='view_my_basket'),
    path('add_basket_item/<str:chapter>/<str:ref_code_book>/<int:price>/',views.add_basket_item, name='add_basket_item'),
    path('check_out_payment/',views.check_out_payment, name='check_out_payment'),
    path('my_basket/<str:chapter>/<str:videos_url>/',views.my_basket, name='my_basket'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('add_whachtime/',views.add_whachtime, name='add_whachtime'),
    path('pay_success/',views.pay_success, name='pay_success'),
    path('pay_cancel/',views.pay_cancel, name='pay_cancel'),
    path('create_invoice/',views.create_invoice, name='create_invoice'),
    path('my_purchases/',views.my_purchases_items, name='my_purchases'),
    path('show_video/<str:chapter_title>/<str:part_title>/<str:part_video>/',views.show_video, name='show_video'),
    path('search/',views.searchbar, name='search'),
    path('lesson_details_searchbar/<str:ref_code_book>/<str:chapter_title>/',views.lesson_details_searchbar, name='lesson_details_searchbar'),
    path('book_content/<str:ref_code_book>/', views.book_content, name='book_content'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_class/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
     path('admin/', admin.site.urls),
     path('captcha/', include('captcha.urls')),
     path('tinymce/', include('tinymce.urls')),
     path('', include(('homepage.urls', 'homepage'), namespace='homepage')),
     path('accounts/', include(('accounts.urls','accounts'),namespace='accounts')),
     path('partnership/', include(('partnership.urls','partnership'),namespace='partnership')),
     path('contact_us/', include(('contact_us.urls','contact_us'),namespace='contact_us')),
     path('blogs/', include(('blogs.urls','blogs'),namespace='blogs')),
     path('primary/', include(('primary.urls','primary'),namespace='primary')),
     path('favicon.ico', RedirectView.as_view(url='/staticfiles/favico/favicon.ico')),
     path('reset/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),
         name="password_reset_confirm"),
     path('accounts/reset_password_sent/', 
         auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), 
         name='password_reset_done'),
     path('accounts/reset_password_complete/', 
         auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), 
         name='password_reset_complete'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField

class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name="Τίτλος")
    author = models.ForeignKey(User, on_delete=models.CASCADE,null=True, blank=True, verbose_name="Συγγραφέας")
    content = HTMLField(null=True,blank=True,verbose_name="Περιεχόμενο")
    image = models.URLField(max_length=1000, null=True, blank=True, verbose_name="Εικόνα (URL)")  # URL Εικόνας
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Ημερομηνία Δημιουργίας")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Τελευταία Ενημέρωση")

    class Meta:
        ordering = ['-created_at']  # Πρόσφατα άρθρα πρώτα
    
    def __str__(self):
        return self.title + '|' + str(self.author).title()

blogs/views.py
from .models import Post
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render

def news(request):
    posts = Post.objects.all().order_by('-created_at')  # Νεότερα πρώτα
    context = {'posts': posts}
    return render(request, 'news.html', context)

def details(request, pk, author_id):
    post = get_object_or_404(Post, pk=pk)  # Αντικείμενο ή 404
    author = get_object_or_404(User, pk=author_id)

    context = {
        'post': post,  # Δεν χρειάζεται .values(), το object είναι προσβάσιμο στο template
        'username': author.username,
    }
    return render(request, 'details.html', context)

blogs/templates/blogs/details.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="el">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blogs/details.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
    <title>Ανακοινώσεις</title>
</head>
<body>
    
    <h1>{{ post.title }}</h1>
    <p id="author">Από: <span id='username'>{{ username }}</span></p>
    <br/>
    <img class="media" src="{{ post.image}}" alt="{{ post.title }}">
    <br/><br/>
    <br/>
    <div class='article'>
        <p>{{post.content|safe}}</p>
    </div>
    <br/> <br/>
    
    
    <a href="{% url 'homepage:homepage' %}" class="button1">Αρχική Σελίδα</a>
    
    <a onClick="javascript:history.go(-1);" class="button">Πίσω</a>

</body>

</html>
{% endblock content %}

blogs/templates/blogs/news.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="el">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blogs/news.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'homepage/favicon.ico' %}" >
    <title>Ανακοινώσεις</title>
</head>
<body>
    
    <h1>Ανακοινώσεις</h1>
    {% for i in posts %}
        <a href="{% url 'blogs:details' i.pk i.author_id %}">
            <img class='media' src="{{ i.image }}" alt="{{ i.title }}">
        </a></br>
        <a class='link' href="{% url 'blogs:details' i.pk i.author_id %}">{{i.title}}
        <p id="text1">{{i.create_at}}</p>
        <hr>   
    {% endfor %}
    
    <a href="{% url 'homepage:homepage' %}" class="button">Αρχική Σελίδα</a>
    
</body>
</html>
{% endblock content %}